[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
# on_path = '.*'

[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

[[plugins]] #括弧の自動補完
# lexima
repo = 'cohama/lexima.vim'
on_i = 1
hook_source='''
    inoremap <C-l> <C-r>=lexima#insmode#leave(1, '<LT>C-G>U<LT>RIGHT>')<CR>
    call lexima#add_rule({'char': '<C-h>', 'at': '(\%#)',   'delete': 1})
    call lexima#add_rule({'char': '<C-h>', 'at': '{\%#}',   'delete': 1})
    call lexima#add_rule({'char': '<C-h>', 'at': '\[\%#\]', 'delete': 1})
    call lexima#add_rule({'char': '<C-h>', 'at': '"\%#"',   'delete': 1})
    call lexima#add_rule({'char': '<C-h>', 'at': "'\\%#'",  'delete': 1})
    call lexima#add_rule({'char': '<C-h>', 'at': '`\%#`',   'delete': 1})
'''

[[plugins]] #検索
repo = 'jremmen/vim-ripgrep'
on_cmd = ['Rg']
