

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview "ポップアップを表示しない
  let g:jedi#completions_command = "<C-j>"
  let g:jedi#popup_on_dot = 0
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
